# -*- coding: utf-8 -*-
"""IntegracaoDados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WBjb3RVRS9LQg7RQXHL3N8EJ9mVMaa5
"""

!pip install pyspark

import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, concat, lit

from google.colab import drive
drive.mount('/content/drive')

spark = SparkSession.builder.appName('CSV_Reader').getOrCreate()

# Caminho da pasta onde os arquivos foram extraídos
path = '/content/dados_extraidos/'

produtos = spark.read.csv(path + 'produtos.csv', header=True, inferSchema=True)
clientes = spark.read.csv(path + 'clientes.csv', header=True, inferSchema=True)
itens_pedido = spark.read.csv(path + 'itens_pedido.csv', header=True, inferSchema=True)
pedidos = spark.read.csv(path + 'pedidos.csv', header=True, inferSchema=True)

import os
# Listando os arquivos no Drive para conferir os nomes exatos
os.listdir('/content/drive/MyDrive/')

import zipfile

# Caminho do arquivo ZIP no seu Drive
caminho_zip = '/content/drive/MyDrive/Material de apoio - M27.zip'
# Pasta de destino local no Colab
pasta_destino = '/content/dados_extraidos'

with zipfile.ZipFile(caminho_zip, 'r') as zip_ref:
    zip_ref.extractall(pasta_destino)

print(f'Arquivos extraídos com sucesso para: {pasta_destino}')

# Listar o que foi extraído para conferir os caminhos
os.listdir(pasta_destino)

join_pedidos_clientes_df = pedidos.join(clientes, pedidos.id_cliente == clientes.id_cliente, 'inner')
join_pedidos_clientes_df = pedidos.join(clientes, 'id_cliente')

# Tipos de join disponíveis:
# inner
# outer
# left_outer
# right_outer

pedidos.show(5)
clientes.show(5)
join_pedidos_clientes_df.show(5)

join_itens_pedido_df = itens_pedido.join(pedidos, 'id_pedido').join(produtos, 'id_produto')
join_itens_pedido_df.show(5)

join_pedidos_entregues_df = pedidos.filter(col('status_pedido') == 'canceled').join(clientes, 'id_cliente')
join_pedidos_entregues_df.show(5)

pedidos_contas_df = pedidos.withColumn('id_pedido_cliente', concat(col('id_pedido'), lit('-'), col('id_cliente')))

colunas = pedidos_contas_df.columns
print(colunas)

colunas.remove('id_pedido_cliente')
colunas.insert(0, 'id_pedido_cliente')

pedidos_reoganizar_df = pedidos_contas_df.select(colunas)
pedidos_reoganizar_df.show(n=5, truncate=False)

join_itens_pedido_df.write.mode('overwrite').option('header', 'true').parquet('drive/MyDrive/Colab Notebook/spark/data/output/join_itens_pedido_parquet')

spark.read.option('header', 'true').parquet('drive/MyDrive/Colab Notebook/spark/data/output/join_itens_pedido_parquet').show(5)

spark.stop()